"""Closed-loop capture/decode probe.

1. Loads a page in Chromium at a given DPR.
2. Mounts the drop-in and renders its real carrier overlay on a tag.
3. Captures the tag via html-to-image.toPng() (the actual call the
   drop-in uses inside src/dropin/capture.ts).
4. Writes the PNG and runs it through decoder/decode.ts via the project CLI.

Reports the correlation score for each DPR so we can see what the
SVG -> canvas resampling step actually does to the v2 carrier.
"""
import json, os, subprocess, sys, tempfile, base64
from playwright.sync_api import sync_playwright

PP = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DROPIN = open(f'{PP}/dist/pixelprovenance-dropin.js').read()
REGISTRY = [
    {
        'path': 'shop/card',
        'type': 'card',
        'depth': 2,
        'source': {'file': 'src/Card.tsx', 'line': 12, 'column': 5},
    },
]
# 200x120 JPEG of coloured noise, encoded at q70 so it has real artifacts.
# Generated by:
#   magick -size 200x120 xc: +noise random -quality 70 jpeg:-
def make_jpeg_b64(width=200, height=120, quality=70):
    r = subprocess.run(
        ['magick', '-size', f'{width}x{height}', 'xc:', '+noise', 'random',
         '-quality', str(quality), 'jpeg:-'],
        capture_output=True, check=True,
    )
    return base64.b64encode(r.stdout).decode('ascii')


JPEG_B64 = make_jpeg_b64()
PAGE = """<!doctype html><html><head>
<meta charset="utf-8">
<style>
  body { font: 15px system-ui; background: #f7f6f2; color: #222; margin: 0; padding: 24px; }
  .card { position: relative; width: 320px; padding: 24px; background: #fff; border: 1px solid #ddd; }
  .card img { display: block; width: 100%%; height: 160px; object-fit: cover; }
</style>
</head><body data-pp-page="shop">
<section class="card" data-pp="card" data-pp-source="src/Card.tsx:12:5">
  <h2>Card title</h2>
  <img id="hero" src="data:image/jpeg;base64,%s" alt="hero">
  <p>Card body text</p>
</section>
<script data-pp-page="shop" data-pp-enabled="true">%s</script>
</body></html>""" % (JPEG_B64, DROPIN)

OUT = tempfile.mkdtemp(prefix='pp-roundtrip-')
reg_path = os.path.join(OUT, 'reg.json')
open(reg_path, 'w').write(json.dumps(REGISTRY))


def decode(png_path, scale):
    r = subprocess.run(
        ['npx', 'tsx', 'decoder/decode.ts', png_path, '--registry', reg_path, '--scale', str(scale), '--json'],
        cwd=PP, capture_output=True, text=True,
    )
    if r.returncode not in (0, 1):
        raise RuntimeError(f'decode failed: {r.stderr}')
    return json.loads(r.stdout) if r.stdout.strip() else []


def capture(dpr):
    """Capture the page the way the drop-in's crop flow does it: render the
    full body via html-to-image.toCanvas, then slice out the .card rect."""
    with sync_playwright() as pw:
        browser = pw.chromium.launch()
        ctx = browser.new_context(device_scale_factor=dpr, viewport={'width': 600, 'height': 600})
        page = ctx.new_page()
        page.set_content(PAGE)
        page.add_script_tag(content=DROPIN)
        page.wait_for_function(
            "Boolean(document.querySelector('[data-pixelprovenance-path=\"shop/card\"]'))",
            timeout=5000,
        )
        # Same call as src/dropin/capture.ts:defaultCaptureRoot.
        info = page.evaluate(
            """() => {
                const layer = document.querySelector('[data-pp-signal-layer]');
                const tile = document.querySelector('[data-pixelprovenance-path="shop/card"]');
                const card = document.querySelector('.card');
                // Sample a pixel through html-to-image's rendering pipeline by
                // using a CSS selector visible to screenshot.
                const rect = card.getBoundingClientRect();
                return {
                    hasLayer: Boolean(layer),
                    hasTile: Boolean(tile),
                    layerParent: layer && layer.parentElement && layer.parentElement.tagName,
                    tileStyle: tile && tile.style.cssText.slice(0, 400),
                    tileRect: tile && tile.getBoundingClientRect(),
                    cardRect: { left: rect.left, top: rect.top, width: rect.width, height: rect.height },
                    bodyBg: getComputedStyle(document.body).backgroundColor,
                    cardBg: getComputedStyle(card).backgroundColor,
                    cardChildren: [...card.children].map(c => c.tagName),
                };
            }"""
        )
        print('DOM check:', json.dumps(info, indent=2))
        data_url = page.evaluate(
            """async () => {
                const m = await import('https://esm.sh/html-to-image@1.11.13');
                return await m.toPng(document.body, {
                    pixelRatio: window.devicePixelRatio,
                    cacheBust: true,
                });
            }"""
        )
        # Slice out the .card rect from the body capture, exactly like
        # sliceCanvas in src/dropin/capture.ts.
        rect = page.evaluate(
            """() => {
                const r = document.querySelector('.card').getBoundingClientRect();
                return { x: r.left + window.scrollX, y: r.top + window.scrollY,
                         w: r.width, h: r.height };
            }"""
        )
        browser.close()
    import re, base64
    m = re.match(r'^data:image/png;base64,(.+)$', data_url)
    if not m:
        raise RuntimeError(f'unexpected data URL: {data_url[:60]}')
    raw = base64.b64decode(m.group(1))
    # Use Playwright/Pillow-free slice: decode with the stdlib? No — easiest
    # is to round-trip through Chromium again. Skip: dump full body PNG and
    # rely on decodePng to find the carrier wherever it is.
    png_path = f'/tmp/pp-roundtrip-dpr{dpr}.png'
    open(png_path, 'wb').write(raw)
    return png_path, rect


results = []
for dpr in (1, 2):
    png, rect = capture(dpr)
    decoded = decode(png, dpr)
    best = decoded[0] if decoded else None
    results.append({
        'dpr': dpr,
        'png': png,
        'png_bytes': os.path.getsize(png),
        'card_rect_css': rect,
        'best_match': best,
    })

print(json.dumps(results, indent=2))